using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using SMS.Modules.Demand.Data;
using SMS.Modules.Demand.Domain;
using SMS.Modules.Demand.Models;
using SMS.Modules.Demand.Repositories;
using SMS.Shared.Common;
using SMS.Shared.Exceptions;
using Xunit;

namespace SMS.Modules.Demand.Tests;

/// <summary>
/// A29-P5-11 §6.2 — editing a DRAFT purchase order the system raised for a sale order line: what the
/// system chose stays on record beside what the team changed it to, every change is reported field
/// by field for the audit log, the sale order line follows the PO, and a PO can be split across
/// suppliers. Real repository over a real in-memory DemandDbContext throughout.
/// </summary>
public class PurchaseOrderModificationTests
{
    private const int Creator = 11;
    private const int Editor = 22;
    private const string Cable = "4mm cable";

    private sealed record Harness(
        DemandDbContext Db, PurchaseOrderRepository Repo, Guid OrgId,
        Guid SupplierA, Guid SupplierB, Guid Variant, Guid PoUuid, Guid OrderUuid, Guid LineUuid, int PoId);

    // A CONFIRMED order selling 100 at 40, 40 of which is short; the system bought the 40 at 25 from A.
    private static async Task<Harness> NewHarness(string source = "BACK_TO_BACK", bool linked = true, string status = "DRAFT")
    {
        var orgId = Guid.NewGuid();
        var db = new DemandDbContext(
            new DbContextOptionsBuilder<DemandDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options,
            new StaticTenantContext { OrganizationId = orgId });
        var repo = new PurchaseOrderRepository(db, NullLogger<PurchaseOrderRepository>.Instance);

        var variant = Guid.NewGuid();
        var supplierA = Guid.NewGuid();
        var supplierB = Guid.NewGuid();

        var order = new SaleOrder
        {
            SoNumber = "SO-2026-00042", PartnerId = Guid.NewGuid(), OrderDate = DateTime.UtcNow.Date,
            CurrencyId = Guid.NewGuid(), Status = "CONFIRMED", DeliveryMode = "SELF_PICKUP", CreatedBy = Creator,
            TraceId = Guid.NewGuid(),
            Lines = { new SaleOrderLine { VariantUuid = variant, Quantity = 100m, UnitPrice = 40m, LineTotal = 4000m,
                                          FulfillmentMode = "BACK_TO_BACK", DeficitQty = 40m, Status = "OPEN",
                                          Margin = 15m, MarginPercent = 37.5m } }
        };
        db.SaleOrders.Add(order);
        await db.SaveChangesAsync();
        var line = order.Lines.Single();

        var created = await repo.CreateFromSaleOrderDeficitAsync(new SaleOrderDeficitPo(
            source, "DRAFT", order.TraceId, order.Id, line.Id, order.SoNumber, supplierA, "Vendor A", variant, 40m, 25m, null), Creator);

        var po = await db.PurchaseOrders.Include(p => p.Lines).SingleAsync(p => p.UUID == created.Uuid);
        po.Lines.Single().ItemDescription = Cable;
        po.Status = status;
        if (!linked)
        {
            po.Source = "MANUAL"; po.LinkedSoId = null; po.LinkedSoLineId = null;
            po.AutoGeneratedQty = null; po.AutoGeneratedPrice = null; po.AutoSelectedSupplierId = null;
        }
        else
        {
            line.LinkedPoId = po.Id;
            line.SelectedSupplierId = supplierA;
        }
        await db.SaveChangesAsync();
        db.ChangeTracker.Clear();

        return new Harness(db, repo, orgId, supplierA, supplierB, variant, po.UUID, order.UUID, line.UUID, po.Id);
    }

    private static PatchPoRequest Lines(Harness h, decimal qty, decimal price, params CreatePoLineRequest[] extra) => new()
    {
        Lines =
        [
            new CreatePoLineRequest { VariantUuid = h.Variant, ItemDescription = Cable, UnitOfMeasure = "PC", Quantity = qty, UnitPrice = price },
            .. extra
        ]
    };

    private static Task<PurchaseOrder> Po(Harness h) =>
        h.Db.PurchaseOrders.AsNoTracking().Include(p => p.Lines).SingleAsync(p => p.UUID == h.PoUuid);

    private static Task<SaleOrderLine> SoLine(Harness h) =>
        h.Db.SaleOrderLines.AsNoTracking().SingleAsync(l => l.UUID == h.LineUuid);

    // ── The audit trail: what changed ────────────────────────────────────────

    [Fact]
    public async Task Changing_a_lines_quantity_is_reported_with_the_old_and_new_value()
    {
        var h = await NewHarness();

        var changes = await h.Repo.UpdateAsync(h.PoUuid, Lines(h, qty: 25m, price: 25m), Editor);

        changes.Should().ContainSingle().Which.Should().Be(new PoFieldChange($"Quantity — {Cable}", "40", "25"));
    }

    [Fact]
    public async Task Changing_a_lines_price_is_reported()
    {
        var h = await NewHarness();

        var changes = await h.Repo.UpdateAsync(h.PoUuid, Lines(h, qty: 40m, price: 22.5m), Editor);

        changes.Should().ContainSingle().Which.Should().Be(new PoFieldChange($"Unit price — {Cable}", "25", "22.5"));
    }

    [Fact]
    public async Task Changing_the_supplier_is_reported_by_name()
    {
        var h = await NewHarness();

        var changes = await h.Repo.UpdateAsync(h.PoUuid,
            new PatchPoRequest { SupplierId = h.SupplierB, SupplierName = "Vendor B" }, Editor);

        changes.Should().ContainSingle().Which.Should().Be(new PoFieldChange("Supplier", "Vendor A", "Vendor B"));
    }

    [Fact]
    public async Task Adding_an_item_and_removing_one_are_each_reported()
    {
        var h = await NewHarness();
        var other = Guid.NewGuid();

        var added = await h.Repo.UpdateAsync(h.PoUuid, Lines(h, 40m, 25m,
            new CreatePoLineRequest { VariantUuid = other, ItemDescription = "Connector", Quantity = 10m, UnitPrice = 3m }), Editor);
        added.Should().ContainSingle().Which.Should().Be(new PoFieldChange("Line added", null, "Connector × 10 @ 3"));

        h.Db.ChangeTracker.Clear();
        var removed = await h.Repo.UpdateAsync(h.PoUuid, Lines(h, 40m, 25m), Editor);
        removed.Should().ContainSingle().Which.Should().Be(new PoFieldChange("Line removed", "Connector × 10 @ 3", null));
    }

    [Fact]
    public async Task Header_fields_are_reported_too()
    {
        var h = await NewHarness();
        var date = new DateTime(2026, 10, 1);

        var changes = await h.Repo.UpdateAsync(h.PoUuid, new PatchPoRequest
        {
            Title = "Cable top-up", Notes = "Deliver to dock 3", DeliveryDate = date, DeliveryWarehouseName = "Central"
        }, Editor);

        changes.Select(c => c.Field).Should().BeEquivalentTo("Title", "Notes", "Delivery date", "Delivery warehouse");
        changes.Single(c => c.Field == "Delivery date").NewValue.Should().Be("2026-10-01");
    }

    [Fact]
    public async Task Replacing_the_lines_leaves_a_total_made_of_the_new_lines_only()
    {
        // Regression: the lines are replaced wholesale, and the total was summed while the old lines
        // were still in the collection alongside the new ones.
        var h = await NewHarness();

        await h.Repo.UpdateAsync(h.PoUuid, Lines(h, qty: 25m, price: 20m), Editor);

        var po = await Po(h);
        po.Lines.Should().ContainSingle();
        po.TotalAmount.Should().Be(500m);
    }

    [Fact]
    public async Task A_patch_that_changes_nothing_reports_nothing()
    {
        var h = await NewHarness();

        (await h.Repo.UpdateAsync(h.PoUuid, Lines(h, qty: 40m, price: 25m), Editor)).Should().BeEmpty();
    }

    [Fact]
    public async Task A_hand_made_po_is_not_audited_field_by_field()
    {
        var h = await NewHarness(linked: false);

        var changes = await h.Repo.UpdateAsync(h.PoUuid, Lines(h, qty: 25m, price: 25m), Editor);

        changes.Should().BeEmpty("only a PO the system raised for a sale order gets the field-level trail");
        (await Po(h)).Lines.Single().Quantity.Should().Be(25m, "the edit itself still happens");
    }

    [Fact]
    public async Task A_po_that_is_no_longer_draft_cannot_be_edited()
    {
        var h = await NewHarness(status: "APPROVED");

        var act = () => h.Repo.UpdateAsync(h.PoUuid, Lines(h, 25m, 25m), Editor);

        await act.Should().ThrowAsync<UnprocessableEntityException>().WithMessage("*Only DRAFT*");
    }

    // ── What the system chose is kept ────────────────────────────────────────

    [Fact]
    public async Task The_auto_generated_values_survive_every_edit_untouched()
    {
        var h = await NewHarness();

        await h.Repo.UpdateAsync(h.PoUuid, new PatchPoRequest
        {
            SupplierId = h.SupplierB, SupplierName = "Vendor B",
            Lines = Lines(h, qty: 100m, price: 18m).Lines
        }, Editor);

        var po = await Po(h);
        po.AutoGeneratedQty.Should().Be(40m);
        po.AutoGeneratedPrice.Should().Be(25m);
        po.AutoSelectedSupplierId.Should().Be(h.SupplierA);
        po.Lines.Single().Quantity.Should().Be(100m);
        po.SupplierId.Should().Be(h.SupplierB);
    }

    [Fact]
    public async Task Editing_a_po_never_disturbs_its_links_to_the_sale_order()
    {
        var h = await NewHarness();
        var before = await Po(h);

        await h.Repo.UpdateAsync(h.PoUuid, Lines(h, 25m, 20m), Editor);

        var after = await Po(h);
        after.Source.Should().Be("BACK_TO_BACK");
        after.LinkedSoId.Should().Be(before.LinkedSoId);
        after.LinkedSoLineId.Should().Be(before.LinkedSoLineId);
        after.TraceId.Should().Be(before.TraceId);
    }

    // ── The tracking read model ──────────────────────────────────────────────

    [Fact]
    public async Task A_fresh_auto_po_shows_the_system_choice_with_nothing_modified()
    {
        var h = await NewHarness();

        var detail = (await h.Repo.GetByIdAsync(h.PoUuid))!;

        detail.Source.Should().Be("BACK_TO_BACK");
        detail.LinkedSaleOrderUuid.Should().Be(h.OrderUuid);
        detail.LinkedSaleOrderNumber.Should().Be("SO-2026-00042");
        var auto = detail.AutoGenerated.Should().NotBeNull().And.Subject.As<PoAutoGeneratedModel>();
        auto.Qty.Should().Be(40m);
        auto.Price.Should().Be(25m);
        auto.SupplierId.Should().Be(h.SupplierA);
        auto.CurrentQty.Should().Be(40m);
        auto.CurrentPrice.Should().Be(25m);
        auto.CurrentSupplierId.Should().Be(h.SupplierA);
        auto.IsModified.Should().BeFalse();
    }

    [Fact]
    public async Task Each_modified_value_is_flagged_against_what_the_system_chose()
    {
        var h = await NewHarness();
        await h.Repo.UpdateAsync(h.PoUuid, new PatchPoRequest
        {
            SupplierId = h.SupplierB, SupplierName = "Vendor B",
            Lines = Lines(h, qty: 100m, price: 18m).Lines
        }, Editor);
        h.Db.ChangeTracker.Clear();

        var auto = (await h.Repo.GetByIdAsync(h.PoUuid))!.AutoGenerated!;

        auto.QtyModified.Should().BeTrue();
        auto.PriceModified.Should().BeTrue();
        auto.SupplierModified.Should().BeTrue();
        auto.CurrentQty.Should().Be(100m);
        auto.CurrentPrice.Should().Be(18m);
        auto.CurrentSupplierId.Should().Be(h.SupplierB);
        auto.Qty.Should().Be(40m, "the original is still there to compare against");
        auto.IsModified.Should().BeTrue();
    }

    [Fact]
    public async Task Only_the_value_that_changed_is_flagged()
    {
        var h = await NewHarness();
        await h.Repo.UpdateAsync(h.PoUuid, Lines(h, qty: 25m, price: 25m), Editor);
        h.Db.ChangeTracker.Clear();

        var auto = (await h.Repo.GetByIdAsync(h.PoUuid))!.AutoGenerated!;

        (auto.QtyModified, auto.PriceModified, auto.SupplierModified).Should().Be((true, false, false));
    }

    [Fact]
    public async Task Items_the_team_added_are_counted_not_mistaken_for_a_quantity_change()
    {
        var h = await NewHarness();
        await h.Repo.UpdateAsync(h.PoUuid, Lines(h, 40m, 25m,
            new CreatePoLineRequest { VariantUuid = Guid.NewGuid(), ItemDescription = "Connector", Quantity = 10m, UnitPrice = 3m }), Editor);
        h.Db.ChangeTracker.Clear();

        var auto = (await h.Repo.GetByIdAsync(h.PoUuid))!.AutoGenerated!;

        auto.AddedLineCount.Should().Be(1);
        auto.QtyModified.Should().BeFalse();
        auto.IsModified.Should().BeTrue();
    }

    [Fact]
    public async Task A_hand_made_po_has_no_auto_generated_section_and_no_sale_order()
    {
        var h = await NewHarness(linked: false);

        var detail = (await h.Repo.GetByIdAsync(h.PoUuid))!;

        detail.Source.Should().Be("MANUAL");
        detail.AutoGenerated.Should().BeNull();
        detail.LinkedSaleOrderUuid.Should().BeNull();
    }

    // ── The sale order line follows the PO ───────────────────────────────────

    [Fact]
    public async Task A_price_change_recomputes_the_lines_margin_against_the_new_cost()
    {
        var h = await NewHarness();

        await h.Repo.UpdateAsync(h.PoUuid, Lines(h, qty: 40m, price: 30m), Editor);

        var line = await SoLine(h);
        line.Margin.Should().Be(10.00m, "sells at 40, now costs 30");
        line.MarginPercent.Should().Be(25.00m);
    }

    [Fact]
    public async Task Removing_the_item_the_line_was_bought_for_clears_the_margin()
    {
        var h = await NewHarness();

        await h.Repo.UpdateAsync(h.PoUuid, new PatchPoRequest
        {
            Lines = [new CreatePoLineRequest { VariantUuid = Guid.NewGuid(), ItemDescription = "Something else", Quantity = 5m, UnitPrice = 9m }]
        }, Editor);

        var line = await SoLine(h);
        line.Margin.Should().BeNull("nothing is being bought for this line any more, so there is no cost to measure it against");
        line.MarginPercent.Should().BeNull();
    }

    [Fact]
    public async Task Changing_the_supplier_moves_the_lines_selected_supplier_with_it()
    {
        var h = await NewHarness();

        await h.Repo.UpdateAsync(h.PoUuid, new PatchPoRequest { SupplierId = h.SupplierB, SupplierName = "Vendor B" }, Editor);

        (await SoLine(h)).SelectedSupplierId.Should().Be(h.SupplierB);
    }

    [Fact]
    public async Task A_header_only_edit_leaves_the_lines_margin_alone()
    {
        var h = await NewHarness();

        await h.Repo.UpdateAsync(h.PoUuid, new PatchPoRequest { Notes = "Call ahead" }, Editor);

        (await SoLine(h)).Margin.Should().Be(15m);
    }

    [Fact]
    public async Task Editing_a_hand_made_po_touches_no_sale_order_line()
    {
        var h = await NewHarness(linked: false);

        await h.Repo.UpdateAsync(h.PoUuid, new PatchPoRequest
        {
            SupplierId = h.SupplierB, SupplierName = "Vendor B", Lines = Lines(h, 25m, 5m).Lines
        }, Editor);

        var line = await SoLine(h);
        line.Margin.Should().Be(15m);
        line.SelectedSupplierId.Should().BeNull();
    }

    // ── Split ────────────────────────────────────────────────────────────────

    private static SplitPoRequest Split(Harness h, decimal qty = 15m, decimal? price = null) => new()
    {
        LineUuid = Guid.Empty, Quantity = qty, SupplierId = h.SupplierB, SupplierName = "Vendor B", UnitPrice = price
    };

    private static async Task<SplitPoRequest> SplitOf(Harness h, decimal qty = 15m, decimal? price = null)
    {
        var req = Split(h, qty, price);
        req.LineUuid = (await Po(h)).Lines.Single().UUID;
        return req;
    }

    [Fact]
    public async Task A_split_moves_the_quantity_to_a_new_draft_po_for_the_other_supplier()
    {
        var h = await NewHarness();

        var result = await h.Repo.SplitAsync(h.PoUuid, await SplitOf(h, qty: 15m), Editor);

        var source = await Po(h);
        source.Lines.Single().Quantity.Should().Be(25m);
        source.Lines.Single().LineTotal.Should().Be(625m);
        source.TotalAmount.Should().Be(625m);
        source.SupplierId.Should().Be(h.SupplierA);
        source.Status.Should().Be("DRAFT");

        var split = await h.Db.PurchaseOrders.AsNoTracking().Include(p => p.Lines).SingleAsync(p => p.UUID == result.NewPoUuid);
        split.PoNumber.Should().Be(result.NewPoNumber).And.NotBe(source.PoNumber);
        split.Status.Should().Be("DRAFT");
        split.SupplierId.Should().Be(h.SupplierB);
        split.SupplierName.Should().Be("Vendor B");
        split.CreatedBy.Should().Be(Editor);
        var line = split.Lines.Should().ContainSingle().Subject;
        (line.VariantUuid, line.ItemDescription, line.UnitOfMeasure).Should().Be((h.Variant, Cable, source.Lines.Single().UnitOfMeasure));
        line.Quantity.Should().Be(15m);
        line.UnitPrice.Should().Be(25m, "the line's own price when the request names none");
        split.TotalAmount.Should().Be(375m);
    }

    [Fact]
    public async Task The_split_po_belongs_to_the_same_sale_order_line_and_trace()
    {
        var h = await NewHarness();
        var before = await Po(h);

        var result = await h.Repo.SplitAsync(h.PoUuid, await SplitOf(h), Editor);

        var split = await h.Db.PurchaseOrders.AsNoTracking().SingleAsync(p => p.UUID == result.NewPoUuid);
        split.Source.Should().Be("BACK_TO_BACK");
        split.LinkedSoId.Should().Be(before.LinkedSoId);
        split.LinkedSoLineId.Should().Be(before.LinkedSoLineId);
        split.TraceId.Should().Be(before.TraceId);
        result.TraceId.Should().Be(before.TraceId);
    }

    [Fact]
    public async Task A_drop_ship_split_carries_the_customers_address_to_the_new_po()
    {
        var h = await NewHarness(source: "DROP_SHIP");
        var address = Guid.NewGuid();
        var po = await h.Db.PurchaseOrders.SingleAsync(p => p.UUID == h.PoUuid);
        po.CustomerShippingAddressId = address;
        await h.Db.SaveChangesAsync();
        h.Db.ChangeTracker.Clear();

        var result = await h.Repo.SplitAsync(h.PoUuid, await SplitOf(h), Editor);

        var split = await h.Db.PurchaseOrders.AsNoTracking().SingleAsync(p => p.UUID == result.NewPoUuid);
        (split.Source, split.CustomerShippingAddressId).Should().Be(("DROP_SHIP", address));
    }

    [Fact]
    public async Task The_split_po_is_not_auto_generated_and_the_original_keeps_the_record_of_what_the_system_chose()
    {
        var h = await NewHarness();

        var result = await h.Repo.SplitAsync(h.PoUuid, await SplitOf(h), Editor);

        var split = await h.Db.PurchaseOrders.AsNoTracking().SingleAsync(p => p.UUID == result.NewPoUuid);
        (split.AutoGeneratedQty, split.AutoGeneratedPrice, split.AutoSelectedSupplierId).Should().Be(((decimal?)null, (decimal?)null, (Guid?)null));
        var source = await Po(h);
        (source.AutoGeneratedQty, source.AutoGeneratedPrice, source.AutoSelectedSupplierId).Should().Be((40m, 25m, (Guid?)h.SupplierA));
        (await h.Repo.GetByIdAsync(h.PoUuid))!.AutoGenerated!.QtyModified.Should().BeTrue("40 became 25 on the original");
    }

    [Fact]
    public async Task A_split_uses_the_new_suppliers_price_when_one_is_given()
    {
        var h = await NewHarness();

        var result = await h.Repo.SplitAsync(h.PoUuid, await SplitOf(h, qty: 15m, price: 30m), Editor);

        (await h.Db.PurchaseOrders.AsNoTracking().SingleAsync(p => p.UUID == result.NewPoUuid)).TotalAmount.Should().Be(450m);
    }

    [Fact]
    public async Task A_split_reports_the_change_to_the_original_for_the_audit_log()
    {
        var h = await NewHarness();

        var result = await h.Repo.SplitAsync(h.PoUuid, await SplitOf(h, qty: 15m), Editor);

        result.Changes.Should().Equal(
            new PoFieldChange($"Quantity — {Cable}", "40", "25"),
            new PoFieldChange("Split", null, $"15 → {result.NewPoNumber} (Vendor B)"));
        result.SourcePoUuid.Should().Be(h.PoUuid);
    }

    [Fact]
    public async Task Both_pos_note_the_split_in_their_internal_notes()
    {
        var h = await NewHarness();

        var result = await h.Repo.SplitAsync(h.PoUuid, await SplitOf(h), Editor);

        var source = await Po(h);
        var split = await h.Db.PurchaseOrders.AsNoTracking().SingleAsync(p => p.UUID == result.NewPoUuid);
        source.InternalNotes.Should().Contain($"moved to {result.NewPoNumber}");
        split.InternalNotes.Should().Contain($"Split from {source.PoNumber}");
    }

    [Fact]
    public async Task The_lines_margin_becomes_the_blend_of_what_both_pos_cost()
    {
        // 25 units at 25 and 15 at 35: (625 + 525) / 40 = 28.75; sells at 40 -> margin 11.25 (28.13 percent).
        var h = await NewHarness();

        await h.Repo.SplitAsync(h.PoUuid, await SplitOf(h, qty: 15m, price: 35m), Editor);

        var line = await SoLine(h);
        line.Margin.Should().Be(11.25m);
        line.MarginPercent.Should().Be(28.13m);
    }

    [Fact]
    public async Task A_split_leaves_the_lines_back_pointer_and_selected_supplier_on_the_original_po()
    {
        var h = await NewHarness();

        await h.Repo.SplitAsync(h.PoUuid, await SplitOf(h), Editor);

        var line = await SoLine(h);
        line.LinkedPoId.Should().Be(h.PoId);
        line.SelectedSupplierId.Should().Be(h.SupplierA);
    }

    [Fact]
    public async Task Editing_the_supplier_of_a_split_po_does_not_overwrite_the_lines_selected_supplier()
    {
        var h = await NewHarness();
        var result = await h.Repo.SplitAsync(h.PoUuid, await SplitOf(h), Editor);
        h.Db.ChangeTracker.Clear();

        await h.Repo.UpdateAsync(result.NewPoUuid,
            new PatchPoRequest { SupplierId = Guid.NewGuid(), SupplierName = "Vendor C" }, Editor);

        (await SoLine(h)).SelectedSupplierId.Should().Be(h.SupplierA, "only the line's own PO speaks for it");
    }

    [Fact]
    public async Task A_split_po_can_itself_be_edited_and_is_audited_because_it_is_a_sale_order_po()
    {
        var h = await NewHarness();
        var result = await h.Repo.SplitAsync(h.PoUuid, await SplitOf(h), Editor);
        h.Db.ChangeTracker.Clear();
        var newLine = (await h.Db.PurchaseOrderLines.AsNoTracking().SingleAsync(l => l.PurchaseOrder.UUID == result.NewPoUuid));

        var changes = await h.Repo.UpdateAsync(result.NewPoUuid, new PatchPoRequest
        {
            Lines = [new CreatePoLineRequest { VariantUuid = h.Variant, ItemDescription = Cable, Quantity = 10m, UnitPrice = newLine.UnitPrice }]
        }, Editor);

        changes.Should().ContainSingle().Which.Field.Should().Be($"Quantity — {Cable}");
    }

    // ── Split: what it refuses ───────────────────────────────────────────────

    [Fact]
    public async Task Only_a_draft_po_can_be_split()
    {
        var h = await NewHarness(status: "APPROVED");

        var act = async () => await h.Repo.SplitAsync(h.PoUuid, await SplitOf(h), Editor);

        await act.Should().ThrowAsync<UnprocessableEntityException>().WithMessage("*Only DRAFT*");
    }

    [Fact]
    public async Task A_po_not_raised_for_a_sale_order_cannot_be_split_here()
    {
        var h = await NewHarness(linked: false);

        var act = async () => await h.Repo.SplitAsync(h.PoUuid, await SplitOf(h), Editor);

        await act.Should().ThrowAsync<UnprocessableEntityException>().WithMessage("*raised for a sale order line*");
    }

    [Theory]
    [InlineData(0)]
    [InlineData(-5)]
    [InlineData(40)]   // all of it: that is a change of supplier, not a split
    [InlineData(41)]
    public async Task The_quantity_moved_must_be_more_than_nothing_and_less_than_the_whole_line(int qty)
    {
        var h = await NewHarness();

        var act = async () => await h.Repo.SplitAsync(h.PoUuid, await SplitOf(h, qty), Editor);

        await act.Should().ThrowAsync<BadRequestException>();
        (await h.Db.PurchaseOrders.CountAsync()).Should().Be(1, "a refused split creates nothing");
    }

    [Fact]
    public async Task An_unknown_line_is_not_found()
    {
        var h = await NewHarness();
        var req = Split(h);
        req.LineUuid = Guid.NewGuid();

        var act = () => h.Repo.SplitAsync(h.PoUuid, req, Editor);

        await act.Should().ThrowAsync<NotFoundException>();
    }

    [Fact]
    public async Task A_split_needs_a_supplier_and_a_non_negative_price()
    {
        var h = await NewHarness();

        var noSupplier = await SplitOf(h);
        noSupplier.SupplierId = Guid.Empty;
        await ((Func<Task>)(() => h.Repo.SplitAsync(h.PoUuid, noSupplier, Editor))).Should().ThrowAsync<BadRequestException>();

        var negative = await SplitOf(h, price: -1m);
        await ((Func<Task>)(() => h.Repo.SplitAsync(h.PoUuid, negative, Editor))).Should().ThrowAsync<BadRequestException>();
    }
}
