using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using SMS.Modules.Demand.Controllers;
using SMS.Modules.Demand.Data;
using SMS.Modules.Demand.Domain;
using SMS.Modules.Demand.Models;
using SMS.Modules.Demand.Repositories;
using SMS.Shared.Authorization;
using SMS.Shared.Exceptions;
using Xunit;

namespace SMS.Modules.Demand.Tests;

// ── Test builder ──────────────────────────────────────────────────────────────

file static class QuoteBuild
{
    internal static (QuotationRepository repo, DemandDbContext db) New(Action<DemandDbContext>? seed = null)
    {
        var opts = new DbContextOptionsBuilder<DemandDbContext>()
            .UseInMemoryDatabase(Guid.NewGuid().ToString())
            .Options;
        var db = new DemandDbContext(opts);
        seed?.Invoke(db);
        db.SaveChanges();
        return (new QuotationRepository(db), db);
    }

    internal static CreateQuotationRequest QuotationRequest(
        string sourceType = "STANDALONE",
        Guid? sourceId = null,
        params CreateQuotationLineRequest[] lines) => new()
    {
        Title      = "Test RFQ",
        SourceType = sourceType,
        SourceId   = sourceId,
        DueDate    = DateTime.UtcNow.AddDays(14),
        Lines      = lines.Length > 0 ? [.. lines] : [DefaultLine()]
    };

    internal static CreateQuotationLineRequest DefaultLine(
        string description = "Laptop",
        decimal qty = 2m) => new()
    {
        ItemDescription = description,
        UnitOfMeasure   = "PC",
        Quantity        = qty
    };

    internal static SendQuotationRequest SendRequest(Guid? supplierId = null) => new()
    {
        Suppliers = [new InviteSupplierRequest
        {
            SupplierId   = supplierId ?? Guid.NewGuid(),
            SupplierName = "ACME Corp"
        }]
    };

    internal static RecordVendorResponseRequest VendorResponse(
        Guid quotationLineUuid,
        decimal netUnitPrice,
        decimal qty = 1m,
        string supplierName = "Test Vendor") => new()
    {
        SupplierId   = Guid.NewGuid(),
        SupplierName = supplierName,
        Lines =
        [
            new VendorResponseLineRequest
            {
                QuotationLineUuid = quotationLineUuid,
                NetUnitPrice      = netUnitPrice,
                Quantity          = qty
            }
        ]
    };
}

// ── AC-1: POST with source_type PR links quotation to the PR record ───────────

public class CreateQuotation_Tests
{
    [Fact]
    public async Task Creates_Quotation_With_Status_DRAFT()
    {
        var (repo, db) = QuoteBuild.New();
        var uuid = await repo.CreateAsync(QuoteBuild.QuotationRequest(), createdBy: 1);

        var q = await db.Quotations.FirstAsync(x => x.UUID == uuid);
        q.Status.Should().Be("DRAFT");
    }

    [Fact]
    public async Task Creates_Quotation_Linked_To_PR()
    {
        var (repo, db) = QuoteBuild.New();
        var prUuid = Guid.NewGuid();

        var uuid = await repo.CreateAsync(
            QuoteBuild.QuotationRequest(sourceType: "PR", sourceId: prUuid),
            createdBy: 1);

        var q = await db.Quotations.FirstAsync(x => x.UUID == uuid);
        q.SourceType.Should().Be("PR");
        q.SourceId.Should().Be(prUuid);
    }

    [Fact]
    public async Task Creates_Quotation_With_AutoGenerated_RfqNumber()
    {
        var (repo, _) = QuoteBuild.New();
        var uuid = await repo.CreateAsync(QuoteBuild.QuotationRequest(), createdBy: 1);
        uuid.Should().NotBeEmpty();
    }
}

// ── AC-2: POST /:id/responses records vendor response with line-level pricing ─

public class RecordVendorResponse_Tests
{
    [Fact]
    public async Task Records_Vendor_Response_With_Line_Level_Pricing()
    {
        var (repo, db) = QuoteBuild.New();
        var qUuid = await repo.CreateAsync(QuoteBuild.QuotationRequest(), createdBy: 1);
        await repo.SendAsync(qUuid, QuoteBuild.SendRequest(), modifiedBy: 1);

        var lineUuid = (await db.QuotationLines.FirstAsync()).UUID;

        var responseUuid = await repo.RecordResponseAsync(
            qUuid,
            QuoteBuild.VendorResponse(lineUuid, netUnitPrice: 95m, qty: 2m),
            createdBy: 1);

        var response = await db.VendorResponses
            .Include(r => r.Lines)
            .FirstAsync(r => r.UUID == responseUuid);

        response.Lines.Should().HaveCount(1);
        response.Lines.Single().NetUnitPrice.Should().Be(95m);
        response.Lines.Single().Quantity.Should().Be(2m);
        response.Lines.Single().LineTotal.Should().Be(190m);
        response.TotalAmount.Should().Be(190m);
    }

    [Fact]
    public async Task Throws_BadRequest_For_Unknown_QuotationLine()
    {
        var (repo, _) = QuoteBuild.New();
        var qUuid = await repo.CreateAsync(QuoteBuild.QuotationRequest(), createdBy: 1);
        await repo.SendAsync(qUuid, QuoteBuild.SendRequest(), modifiedBy: 1);

        var act = () => repo.RecordResponseAsync(
            qUuid,
            QuoteBuild.VendorResponse(Guid.NewGuid(), 100m),
            createdBy: 1);

        await act.Should().ThrowAsync<BadRequestException>();
    }
}

// ── AC-3: GET /:id/comparison returns responses sorted by net_unit_price ──────

public class GetComparison_Tests
{
    [Fact]
    public async Task Comparison_Returns_Responses_Sorted_By_TotalAmount_Ascending()
    {
        var (repo, db) = QuoteBuild.New();
        var qUuid = await repo.CreateAsync(QuoteBuild.QuotationRequest(), createdBy: 1);
        await repo.SendAsync(qUuid, QuoteBuild.SendRequest(), modifiedBy: 1);

        var lineUuid = (await db.QuotationLines.FirstAsync()).UUID;

        await repo.RecordResponseAsync(
            qUuid,
            QuoteBuild.VendorResponse(lineUuid, netUnitPrice: 200m, qty: 1m, supplierName: "Expensive Corp"),
            createdBy: 1);

        await repo.RecordResponseAsync(
            qUuid,
            QuoteBuild.VendorResponse(lineUuid, netUnitPrice: 100m, qty: 1m, supplierName: "Cheap Corp"),
            createdBy: 2);

        var comparison = await repo.GetComparisonAsync(qUuid);

        comparison.Should().HaveCount(2);
        comparison[0].TotalAmount.Should().Be(100m);
        comparison[0].SupplierName.Should().Be("Cheap Corp");
        comparison[1].TotalAmount.Should().Be(200m);
    }

    [Fact]
    public async Task Comparison_Includes_Line_Level_Detail()
    {
        var (repo, db) = QuoteBuild.New();
        var qUuid = await repo.CreateAsync(QuoteBuild.QuotationRequest(), createdBy: 1);
        await repo.SendAsync(qUuid, QuoteBuild.SendRequest(), modifiedBy: 1);

        var lineUuid = (await db.QuotationLines.FirstAsync()).UUID;

        await repo.RecordResponseAsync(
            qUuid,
            QuoteBuild.VendorResponse(lineUuid, netUnitPrice: 150m, qty: 1m),
            createdBy: 1);

        var comparison = await repo.GetComparisonAsync(qUuid);

        comparison.Single().Lines.Should().HaveCount(1);
        comparison.Single().Lines.Single().NetUnitPrice.Should().Be(150m);
        comparison.Single().Lines.Single().QuotationLineUuid.Should().Be(lineUuid);
    }
}

// ── AC-4: Award by Requester returns 403 (permission guard) ──────────────────

public class AwardQuotation_Authorization_Tests
{
    [Fact]
    public void AwardQuotation_Requires_RFQ_MANAGE_Permission()
    {
        var method = typeof(QuotationsController)
            .GetMethod(nameof(QuotationsController.AwardQuotation));

        method.Should().NotBeNull();

        var attr = method!.GetCustomAttributes(typeof(RequirePermissionAttribute), inherit: false)
            .Cast<RequirePermissionAttribute>()
            .FirstOrDefault();

        attr.Should().NotBeNull("AwardQuotation must be guarded by RequirePermissionAttribute");
        attr!.Policy.Should().Be($"Permission:{PermissionCodes.RFQ_MANAGE}",
            "only users with RFQ_MANAGE (Procurement Manager) may award — Requester gets 403");
    }
}

// ── AC-5: Award sets AWARDED for winner, REJECTED for all others ──────────────

public class AwardAsync_Tests
{
    [Fact]
    public async Task Award_Sets_Winner_AWARDED_And_Others_REJECTED()
    {
        var (repo, db) = QuoteBuild.New();
        var qUuid = await repo.CreateAsync(QuoteBuild.QuotationRequest(), createdBy: 1);
        await repo.SendAsync(qUuid, QuoteBuild.SendRequest(), modifiedBy: 1);

        var lineUuid = (await db.QuotationLines.FirstAsync()).UUID;

        var response1Uuid = await repo.RecordResponseAsync(
            qUuid, QuoteBuild.VendorResponse(lineUuid, 100m), createdBy: 1);
        var response2Uuid = await repo.RecordResponseAsync(
            qUuid, QuoteBuild.VendorResponse(lineUuid, 120m), createdBy: 2);

        await repo.AwardAsync(qUuid,
            new AwardQuotationRequest { VendorResponseUuid = response1Uuid },
            awardedBy: 99);

        var r1 = await db.VendorResponses.FirstAsync(r => r.UUID == response1Uuid);
        var r2 = await db.VendorResponses.FirstAsync(r => r.UUID == response2Uuid);
        var q  = await db.Quotations.FirstAsync(x => x.UUID == qUuid);

        r1.Status.Should().Be("AWARDED");
        r2.Status.Should().Be("REJECTED");
        q.Status.Should().Be("AWARDED");
    }
}

// ── AC-6: Award with source_type PR updates pr_line.estimated_unit_price ──────

public class AwardPrWriteback_Tests
{
    [Fact]
    public async Task Award_PR_Source_Updates_PrLine_EstimatedUnitPrice()
    {
        var (repo, db) = QuoteBuild.New();
        var prRepo = new RequisitionRepository(db);

        // Create a PR with one line (initial price = 100)
        var prUuid = await prRepo.CreateAsync(
            new CreatePrRequest
            {
                PrTitle       = "Test PR",
                Department    = "IT",
                RequestedDate = DateTime.UtcNow.AddDays(7),
                Priority      = "HIGH",
                Lines =
                [
                    new CreatePrLineRequest
                    {
                        ItemDescription    = "Laptop",
                        UnitOfMeasure      = "PC",
                        Quantity           = 2m,
                        EstimatedUnitPrice = 100m
                    }
                ]
            },
            createdBy: 1);

        var prLine = await db.PrLines.FirstAsync();
        prLine.EstimatedUnitPrice.Should().Be(100m);

        // Create quotation linked to that PR line
        var qUuid = await repo.CreateAsync(new CreateQuotationRequest
        {
            Title      = "RFQ from PR",
            SourceType = "PR",
            SourceId   = prUuid,
            Lines =
            [
                new CreateQuotationLineRequest
                {
                    SourcePrLineUuid = prLine.UUID,
                    ItemDescription  = prLine.ItemDescription,
                    Quantity         = prLine.Quantity
                }
            ]
        }, createdBy: 1);

        await repo.SendAsync(qUuid, QuoteBuild.SendRequest(), modifiedBy: 1);

        var qLineUuid = (await db.QuotationLines
            .FirstAsync(l => l.SourcePrLineUuid == prLine.UUID)).UUID;

        var responseUuid = await repo.RecordResponseAsync(qUuid, new RecordVendorResponseRequest
        {
            SupplierId   = Guid.NewGuid(),
            SupplierName = "Vendor A",
            Lines =
            [
                new VendorResponseLineRequest
                {
                    QuotationLineUuid = qLineUuid,
                    NetUnitPrice      = 85m,
                    Quantity          = 2m
                }
            ]
        }, createdBy: 1);

        await repo.AwardAsync(qUuid,
            new AwardQuotationRequest { VendorResponseUuid = responseUuid },
            awardedBy: 99);

        var updatedPrLine = await db.PrLines.FirstAsync(l => l.UUID == prLine.UUID);
        updatedPrLine.EstimatedUnitPrice.Should().Be(85m);
    }
}

// ── AC-7: Award with source_type PO updates po_line.unit_price ───────────────

public class AwardPoWriteback_Tests
{
    [Fact]
    public async Task Award_PO_Source_Updates_PoLine_UnitPrice()
    {
        var (repo, db) = QuoteBuild.New();

        // Seed a PoLine stub directly
        var poLine = new PoLine
        {
            UUID            = Guid.NewGuid(),
            ItemDescription = "Server",
            Quantity        = 1m,
            UnitPrice       = 5000m
        };
        db.PoLines.Add(poLine);
        await db.SaveChangesAsync();

        // Create quotation linked to that PO line
        var qUuid = await repo.CreateAsync(new CreateQuotationRequest
        {
            Title      = "RFQ from PO",
            SourceType = "PO",
            SourceId   = Guid.NewGuid(),
            Lines =
            [
                new CreateQuotationLineRequest
                {
                    SourcePoLineUuid = poLine.UUID,
                    ItemDescription  = poLine.ItemDescription,
                    Quantity         = 1m
                }
            ]
        }, createdBy: 1);

        await repo.SendAsync(qUuid, QuoteBuild.SendRequest(), modifiedBy: 1);

        var qLineUuid = (await db.QuotationLines
            .FirstAsync(l => l.SourcePoLineUuid == poLine.UUID)).UUID;

        var responseUuid = await repo.RecordResponseAsync(qUuid, new RecordVendorResponseRequest
        {
            SupplierId   = Guid.NewGuid(),
            SupplierName = "Vendor B",
            Lines =
            [
                new VendorResponseLineRequest
                {
                    QuotationLineUuid = qLineUuid,
                    NetUnitPrice      = 4500m,
                    Quantity          = 1m
                }
            ]
        }, createdBy: 1);

        await repo.AwardAsync(qUuid,
            new AwardQuotationRequest { VendorResponseUuid = responseUuid },
            awardedBy: 99);

        var updatedPoLine = await db.PoLines.FirstAsync(l => l.UUID == poLine.UUID);
        updatedPoLine.UnitPrice.Should().Be(4500m);
    }
}

// ── AC-8: Cannot award a CANCELLED quotation ─────────────────────────────────

public class AwardCancelledQuotation_Tests
{
    [Fact]
    public async Task Throws_BadRequest_When_Awarding_Cancelled_Quotation()
    {
        var (repo, _) = QuoteBuild.New();
        var qUuid = await repo.CreateAsync(QuoteBuild.QuotationRequest(), createdBy: 1);
        await repo.SendAsync(qUuid, QuoteBuild.SendRequest(), modifiedBy: 1);
        await repo.CancelAsync(qUuid, "Budget cut", modifiedBy: 1);

        var act = () => repo.AwardAsync(qUuid,
            new AwardQuotationRequest { VendorResponseUuid = Guid.NewGuid() },
            awardedBy: 1);

        await act.Should().ThrowAsync<BadRequestException>()
            .WithMessage("*Cannot transition*");
    }

    [Fact]
    public async Task Throws_BadRequest_When_Awarding_Already_Awarded_Quotation()
    {
        var (repo, db) = QuoteBuild.New();
        var qUuid = await repo.CreateAsync(QuoteBuild.QuotationRequest(), createdBy: 1);
        await repo.SendAsync(qUuid, QuoteBuild.SendRequest(), modifiedBy: 1);

        var lineUuid = (await db.QuotationLines.FirstAsync()).UUID;
        var responseUuid = await repo.RecordResponseAsync(
            qUuid, QuoteBuild.VendorResponse(lineUuid, 100m), createdBy: 1);

        await repo.AwardAsync(qUuid,
            new AwardQuotationRequest { VendorResponseUuid = responseUuid },
            awardedBy: 99);

        var act = () => repo.AwardAsync(qUuid,
            new AwardQuotationRequest { VendorResponseUuid = responseUuid },
            awardedBy: 99);

        await act.Should().ThrowAsync<BadRequestException>()
            .WithMessage("*Cannot transition*");
    }
}
