using FluentAssertions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SMS.Modules.Demand.Controllers;
using SMS.Modules.Demand.Data;
using SMS.Modules.Demand.Models;
using SMS.Modules.Demand.Repositories;
using SMS.Modules.Demand.Services;
using SMS.Shared.Authorization;
using SMS.Shared.Exceptions;
using Xunit;

namespace SMS.Modules.Demand.Tests;

// ── Test builder ──────────────────────────────────────────────────────────────

file static class Build
{
    internal static (RequisitionRepository repo, DemandDbContext db) New(Action<DemandDbContext>? seed = null)
    {
        var opts = new DbContextOptionsBuilder<DemandDbContext>()
            .UseInMemoryDatabase(Guid.NewGuid().ToString())
            .Options;
        var db = new DemandDbContext(opts);
        seed?.Invoke(db);
        db.SaveChanges();
        return (new RequisitionRepository(db), db);
    }

    internal static CreatePrRequest DraftRequest(
        bool requiresQuotation = false,
        params CreatePrLineRequest[] lines) => new()
    {
        PrTitle           = "Test Requisition",
        Department        = "IT",
        RequestedDate     = DateTime.UtcNow.AddDays(7),
        Priority          = "MEDIUM",
        RequiresQuotation = requiresQuotation,
        Lines             = lines.Length > 0 ? [.. lines] : [DefaultLine()]
    };

    internal static CreatePrLineRequest DefaultLine(
        decimal qty = 2m,
        decimal unitPrice = 100m,
        bool requiresQuotation = false) => new()
    {
        ItemDescription    = "Laptop",
        UnitOfMeasure      = "PC",
        Quantity           = qty,
        EstimatedUnitPrice = unitPrice,
        RequiresQuotation  = requiresQuotation
    };
}

// ── AC-1: POST creates PR with status = DRAFT ─────────────────────────────────

public class CreateAsync_Tests
{
    [Fact]
    public async Task Creates_PR_With_Status_DRAFT()
    {
        var (repo, db) = Build.New();

        var uuid = await repo.CreateAsync(Build.DraftRequest(), createdBy: 1);

        var pr = await db.PurchaseRequisitions.FirstOrDefaultAsync(r => r.UUID == uuid);
        pr.Should().NotBeNull();
        pr!.Status.Should().Be("DRAFT");
    }

    [Fact]
    public async Task Creates_PR_With_AutoGenerated_PrNumber()
    {
        var (repo, _) = Build.New();
        var uuid = await repo.CreateAsync(Build.DraftRequest(), createdBy: 1);
        uuid.Should().NotBeEmpty();
    }

    [Fact]
    public async Task Creates_PR_With_System_Generated_TraceId()
    {
        var (repo, db) = Build.New();

        var uuid = await repo.CreateAsync(Build.DraftRequest(), createdBy: 1);

        var pr = await db.PurchaseRequisitions.FirstAsync(r => r.UUID == uuid);
        pr.TraceId.Should().NotBe(Guid.Empty);
    }

    [Fact]
    public async Task TraceId_Is_Present_In_GetById_Response()
    {
        var (repo, db) = Build.New();
        var uuid = await repo.CreateAsync(Build.DraftRequest(), createdBy: 1);

        var detail = await repo.GetByIdAsync(uuid);

        detail.Should().NotBeNull();
        detail!.TraceId.Should().NotBe(Guid.Empty);
    }
}

// ── AC-2: PATCH on a non-DRAFT PR returns 422 ────────────────────────────────

public class PatchAsync_Tests
{
    [Fact]
    public async Task Throws_UnprocessableEntity_When_PR_Is_Not_DRAFT()
    {
        var (repo, db) = Build.New();
        var uuid = await repo.CreateAsync(Build.DraftRequest(), createdBy: 1);

        // Set status directly — workflow engine handles submit in production
        var pr = await db.PurchaseRequisitions.FirstAsync(r => r.UUID == uuid);
        pr.Status = "SUBMITTED";
        await db.SaveChangesAsync();

        var act = () => repo.UpdateAsync(uuid, new PatchPrRequest { PrTitle = "Changed" }, modifiedBy: 1);

        await act.Should().ThrowAsync<UnprocessableEntityException>()
            .WithMessage("*Only DRAFT*");
    }

    [Fact]
    public async Task Succeeds_When_PR_Is_DRAFT()
    {
        var (repo, db) = Build.New();
        var uuid = await repo.CreateAsync(Build.DraftRequest(), createdBy: 1);

        await repo.UpdateAsync(uuid, new PatchPrRequest { PrTitle = "Updated Title" }, modifiedBy: 1);

        var pr = await db.PurchaseRequisitions.FirstAsync(r => r.UUID == uuid);
        pr.PrTitle.Should().Be("Updated Title");
    }
}

// ── AC-3: estimated_total equals sum of line_totals ───────────────────────────

public class EstimatedTotal_Tests
{
    [Fact]
    public async Task EstimatedTotal_Equals_Sum_Of_LineTotals_On_Create()
    {
        var (repo, db) = Build.New();
        var req = Build.DraftRequest(lines:
        [
            Build.DefaultLine(qty: 3m, unitPrice: 50m),
            Build.DefaultLine(qty: 1m, unitPrice: 200m),
            Build.DefaultLine(qty: 10m, unitPrice: 15m)
        ]);

        var uuid = await repo.CreateAsync(req, createdBy: 1);

        var pr = await db.PurchaseRequisitions
            .Include(r => r.Lines)
            .FirstAsync(r => r.UUID == uuid);

        var lineTotal = pr.Lines.Sum(l => l.LineTotal);
        pr.EstimatedTotal.Should().Be(lineTotal);
        pr.EstimatedTotal.Should().Be(3m * 50m + 1m * 200m + 10m * 15m);
    }

    [Fact]
    public async Task LineTotal_Equals_Quantity_Times_UnitPrice()
    {
        var (repo, db) = Build.New();
        var uuid = await repo.CreateAsync(
            Build.DraftRequest(lines: [Build.DefaultLine(qty: 5m, unitPrice: 120m)]),
            createdBy: 1);

        var pr = await db.PurchaseRequisitions
            .Include(r => r.Lines)
            .FirstAsync(r => r.UUID == uuid);

        pr.Lines.Single().LineTotal.Should().Be(5m * 120m);
    }

    [Fact]
    public async Task EstimatedTotal_Recalculated_After_Patch()
    {
        var (repo, db) = Build.New();
        var uuid = await repo.CreateAsync(
            Build.DraftRequest(lines: [Build.DefaultLine(qty: 2m, unitPrice: 100m)]),
            createdBy: 1);

        await repo.UpdateAsync(uuid, new PatchPrRequest
        {
            Lines = [Build.DefaultLine(qty: 5m, unitPrice: 80m)]
        }, modifiedBy: 1);

        var pr = await db.PurchaseRequisitions.FirstAsync(r => r.UUID == uuid);
        pr.EstimatedTotal.Should().Be(5m * 80m);
    }
}

// ── AC-4: requires_quotation flag saved correctly per PR and per line ─────────

public class RequiresQuotation_Tests
{
    [Fact]
    public async Task RequiresQuotation_True_Saved_On_PR()
    {
        var (repo, db) = Build.New();
        var uuid = await repo.CreateAsync(Build.DraftRequest(requiresQuotation: true), createdBy: 1);

        var pr = await db.PurchaseRequisitions.FirstAsync(r => r.UUID == uuid);
        pr.RequiresQuotation.Should().BeTrue();
    }

    [Fact]
    public async Task RequiresQuotation_False_Saved_On_PR()
    {
        var (repo, db) = Build.New();
        var uuid = await repo.CreateAsync(Build.DraftRequest(requiresQuotation: false), createdBy: 1);

        var pr = await db.PurchaseRequisitions.FirstAsync(r => r.UUID == uuid);
        pr.RequiresQuotation.Should().BeFalse();
    }

    [Fact]
    public async Task RequiresQuotation_Saved_Per_Line()
    {
        var (repo, db) = Build.New();
        var req = Build.DraftRequest(lines:
        [
            Build.DefaultLine(requiresQuotation: true),
            Build.DefaultLine(requiresQuotation: false)
        ]);

        var uuid = await repo.CreateAsync(req, createdBy: 1);

        var pr = await db.PurchaseRequisitions
            .Include(r => r.Lines)
            .FirstAsync(r => r.UUID == uuid);

        pr.Lines.Should().HaveCount(2);
        pr.Lines.OrderBy(l => l.LineNo).First().RequiresQuotation.Should().BeTrue();
        pr.Lines.OrderBy(l => l.LineNo).Last().RequiresQuotation.Should().BeFalse();
    }
}
