// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMS.Modules.Logistics.Data;

#nullable disable

namespace SMS.Modules.Logistics.Migrations
{
    [DbContext(typeof(LogisticsDbContext))]
    [Migration("20260915172913_AddDocumentNumberSequences")]
    partial class AddDocumentNumberSequences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("logistics")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ConsigneeUuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ContactPhoneE164")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryIsoCode")
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Line2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValidationNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "CityId");

                    b.HasIndex("OrganizationId", "ValidationStatus");

                    b.ToTable("addresses", "logistics");
                });

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.Carrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("RatePerKg")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("TrackingUrlTemplate")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique();

                    b.ToTable("carriers", "logistics");
                });

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.Consignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualArrivalAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualDispatchAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingFailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("BookingIdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CarrierId")
                        .HasColumnType("int");

                    b.Property<string>("CarrierName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CarrierReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CarrierServiceCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("CodAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CodCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("ConsignmentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DriverPhone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("Eta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Etd")
                        .HasColumnType("datetime2");

                    b.Property<string>("FreightTerms")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MasterAwb")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PickupWindowEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PickupWindowStart")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("ShipFromAddressId")
                        .HasColumnType("int");

                    b.Property<int?>("ShipToAddressId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VehicleNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("ShipFromAddressId");

                    b.HasIndex("ShipToAddressId");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "BookingIdempotencyKey")
                        .IsUnique()
                        .HasFilter("[BookingIdempotencyKey] IS NOT NULL");

                    b.HasIndex("OrganizationId", "ConsignmentNumber")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "MasterAwb");

                    b.HasIndex("OrganizationId", "Status");

                    b.ToTable("consignments", "logistics");
                });

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.ConsignmentDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsignmentId")
                        .HasColumnType("int");

                    b.Property<int?>("ConsignmentStopId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveryOrderId")
                        .HasColumnType("int");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConsignmentStopId");

                    b.HasIndex("DeliveryOrderId");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("ConsignmentId", "DeliveryOrderId")
                        .IsUnique();

                    b.ToTable("consignment_deliveries", "logistics");
                });

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.ConsignmentStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualArrival")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("ConsignmentId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PlannedArrival")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("StopType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("ConsignmentId", "Sequence")
                        .IsUnique();

                    b.ToTable("consignment_stops", "logistics");
                });

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.DeliveryOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("HeldAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HeldBy")
                        .HasColumnType("int");

                    b.Property<string>("HoldReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Incoterm")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("LinesUnknown")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("PromisedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("ShipFromAddressId")
                        .HasColumnType("int");

                    b.Property<int?>("ShipToAddressId")
                        .HasColumnType("int");

                    b.Property<string>("SourceNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("SourceUuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("StatusBeforeHold")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TraceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShipFromAddressId");

                    b.HasIndex("ShipToAddressId");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "DeliveryNumber")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "Status");

                    b.HasIndex("OrganizationId", "SourceType", "SourceUuid");

                    b.ToTable("delivery_orders", "logistics");
                });

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.DeliveryOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("BinUuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveryOrderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFragile")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHazardous")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTemperatureControlled")
                        .HasColumnType("bit");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("LineNo")
                        .HasColumnType("int");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductUuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("QtyDelivered")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("QtyOrdered")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("QtyPacked")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("QtyPicked")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("QtyShipped")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("QtyShort")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShortReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("SourceLineUuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("UnitValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("VariantUuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("DeliveryOrderId", "LineNo")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "VariantUuid");

                    b.ToTable("delivery_order_lines", "logistics");
                });

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.DocumentNumberSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NextValue")
                        .HasColumnType("int");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Prefix", "Year")
                        .IsUnique();

                    b.ToTable("document_number_sequences", "logistics");
                });

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.PackageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveryOrderLineId")
                        .HasColumnType("int");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ShipmentPackageId")
                        .HasColumnType("int");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryOrderLineId");

                    b.HasIndex("ShipmentPackageId");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.ToTable("package_contents", "logistics");
                });

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualArrival")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CarrierId")
                        .HasColumnType("int");

                    b.Property<string>("CarrierName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("DispatchDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EstimatedArrival")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FreightCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OriginWarehouseUuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("PoUuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProofOfDeliveryUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ShipmentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShipmentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Courier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Preparing");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrackingUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("VolumeCbm")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "ShipmentNumber")
                        .IsUnique();

                    b.ToTable("shipments", "logistics");
                });

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.ShipmentPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DeclaredValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DeliveryOrderId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DimWeightKg")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("GrossWeightKg")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVoided")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LengthCm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NetWeightKg")
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PackageBarcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ParentPackageId")
                        .HasColumnType("int");

                    b.Property<string>("SealNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal?>("WidthCm")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryOrderId");

                    b.HasIndex("ParentPackageId");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "PackageBarcode")
                        .IsUnique();

                    b.ToTable("shipment_packages", "logistics");
                });

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.Consignment", b =>
                {
                    b.HasOne("SMS.Modules.Logistics.Domain.Carrier", "Carrier")
                        .WithMany()
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SMS.Modules.Logistics.Domain.Address", "ShipFromAddress")
                        .WithMany()
                        .HasForeignKey("ShipFromAddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SMS.Modules.Logistics.Domain.Address", "ShipToAddress")
                        .WithMany()
                        .HasForeignKey("ShipToAddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Carrier");

                    b.Navigation("ShipFromAddress");

                    b.Navigation("ShipToAddress");
                });

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.ConsignmentDelivery", b =>
                {
                    b.HasOne("SMS.Modules.Logistics.Domain.Consignment", "Consignment")
                        .WithMany("Deliveries")
                        .HasForeignKey("ConsignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMS.Modules.Logistics.Domain.ConsignmentStop", "ConsignmentStop")
                        .WithMany("Deliveries")
                        .HasForeignKey("ConsignmentStopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SMS.Modules.Logistics.Domain.DeliveryOrder", "DeliveryOrder")
                        .WithMany("Consignments")
                        .HasForeignKey("DeliveryOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consignment");

                    b.Navigation("ConsignmentStop");

                    b.Navigation("DeliveryOrder");
                });

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.ConsignmentStop", b =>
                {
                    b.HasOne("SMS.Modules.Logistics.Domain.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SMS.Modules.Logistics.Domain.Consignment", "Consignment")
                        .WithMany("Stops")
                        .HasForeignKey("ConsignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Consignment");
                });

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.DeliveryOrder", b =>
                {
                    b.HasOne("SMS.Modules.Logistics.Domain.Address", "ShipFromAddress")
                        .WithMany()
                        .HasForeignKey("ShipFromAddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SMS.Modules.Logistics.Domain.Address", "ShipToAddress")
                        .WithMany()
                        .HasForeignKey("ShipToAddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ShipFromAddress");

                    b.Navigation("ShipToAddress");
                });

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.DeliveryOrderLine", b =>
                {
                    b.HasOne("SMS.Modules.Logistics.Domain.DeliveryOrder", "DeliveryOrder")
                        .WithMany("Lines")
                        .HasForeignKey("DeliveryOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryOrder");
                });

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.PackageContent", b =>
                {
                    b.HasOne("SMS.Modules.Logistics.Domain.DeliveryOrderLine", "DeliveryOrderLine")
                        .WithMany("PackageContents")
                        .HasForeignKey("DeliveryOrderLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMS.Modules.Logistics.Domain.ShipmentPackage", "ShipmentPackage")
                        .WithMany("Contents")
                        .HasForeignKey("ShipmentPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryOrderLine");

                    b.Navigation("ShipmentPackage");
                });

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.Shipment", b =>
                {
                    b.HasOne("SMS.Modules.Logistics.Domain.Carrier", "Carrier")
                        .WithMany("Shipments")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Carrier");
                });

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.ShipmentPackage", b =>
                {
                    b.HasOne("SMS.Modules.Logistics.Domain.DeliveryOrder", "DeliveryOrder")
                        .WithMany("Packages")
                        .HasForeignKey("DeliveryOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMS.Modules.Logistics.Domain.ShipmentPackage", "ParentPackage")
                        .WithMany("ChildPackages")
                        .HasForeignKey("ParentPackageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DeliveryOrder");

                    b.Navigation("ParentPackage");
                });

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.Carrier", b =>
                {
                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.Consignment", b =>
                {
                    b.Navigation("Deliveries");

                    b.Navigation("Stops");
                });

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.ConsignmentStop", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.DeliveryOrder", b =>
                {
                    b.Navigation("Consignments");

                    b.Navigation("Lines");

                    b.Navigation("Packages");
                });

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.DeliveryOrderLine", b =>
                {
                    b.Navigation("PackageContents");
                });

            modelBuilder.Entity("SMS.Modules.Logistics.Domain.ShipmentPackage", b =>
                {
                    b.Navigation("ChildPackages");

                    b.Navigation("Contents");
                });
#pragma warning restore 612, 618
        }
    }
}
