using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SMS.Modules.Demand.Migrations
{
    /// <inheritdoc />
    public partial class AddPoSourceAndLinkedFields : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<decimal>(
                name: "AutoGeneratedPrice",
                schema: "demand",
                table: "purchase_orders",
                type: "decimal(18,2)",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "AutoGeneratedQty",
                schema: "demand",
                table: "purchase_orders",
                type: "decimal(18,4)",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "AutoSelectedSupplierId",
                schema: "demand",
                table: "purchase_orders",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "CustomerShippingAddressId",
                schema: "demand",
                table: "purchase_orders",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "LinkedSoId",
                schema: "demand",
                table: "purchase_orders",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "LinkedSoLineId",
                schema: "demand",
                table: "purchase_orders",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Source",
                schema: "demand",
                table: "purchase_orders",
                type: "nvarchar(20)",
                maxLength: 20,
                nullable: false,
                defaultValue: "MANUAL");

            migrationBuilder.CreateIndex(
                name: "IX_purchase_orders_LinkedSoId_LinkedSoLineId",
                schema: "demand",
                table: "purchase_orders",
                columns: new[] { "LinkedSoId", "LinkedSoLineId" });

            migrationBuilder.CreateIndex(
                name: "IX_purchase_orders_OrganizationId_TraceId",
                schema: "demand",
                table: "purchase_orders",
                columns: new[] { "OrganizationId", "TraceId" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_purchase_orders_LinkedSoId_LinkedSoLineId",
                schema: "demand",
                table: "purchase_orders");

            migrationBuilder.DropIndex(
                name: "IX_purchase_orders_OrganizationId_TraceId",
                schema: "demand",
                table: "purchase_orders");

            migrationBuilder.DropColumn(
                name: "AutoGeneratedPrice",
                schema: "demand",
                table: "purchase_orders");

            migrationBuilder.DropColumn(
                name: "AutoGeneratedQty",
                schema: "demand",
                table: "purchase_orders");

            migrationBuilder.DropColumn(
                name: "AutoSelectedSupplierId",
                schema: "demand",
                table: "purchase_orders");

            migrationBuilder.DropColumn(
                name: "CustomerShippingAddressId",
                schema: "demand",
                table: "purchase_orders");

            migrationBuilder.DropColumn(
                name: "LinkedSoId",
                schema: "demand",
                table: "purchase_orders");

            migrationBuilder.DropColumn(
                name: "LinkedSoLineId",
                schema: "demand",
                table: "purchase_orders");

            migrationBuilder.DropColumn(
                name: "Source",
                schema: "demand",
                table: "purchase_orders");
        }
    }
}
