using SMS.Shared.Common;

namespace SMS.Modules.Demand.Domain;

internal class PurchaseOrder : ITenantScopedEntity
{
    public int Id { get; set; }
    public Guid UUID { get; set; }
    public Guid TraceId { get; set; }
    public Guid OrganizationId { get; set; }
    public string PoNumber { get; set; } = string.Empty;
    public string? Title { get; set; }
    public Guid SupplierId { get; set; }
    public string SupplierName { get; set; } = string.Empty;
    public string Status { get; set; } = "DRAFT"; // DRAFT | APPROVED | SENT | PARTIALLY_RECEIVED | RECEIVED | PARTIALLY_INVOICED | CLOSED | CANCELLED
    public decimal TotalAmount { get; set; }
    public DateTime? DeliveryDate { get; set; }
    public string? Notes { get; set; }
    public string? InternalNotes { get; set; }
    public Guid? DeliveryWarehouseId { get; set; }
    public string? DeliveryWarehouseName { get; set; }
    public string? SupplierContactMobile { get; set; }  // verified E.164 mobile captured at Send time
    public bool IsActive { get; set; } = true;
    public bool IsDelete { get; set; }
    public int CreatedBy { get; set; }
    public DateTime CreatedDate { get; set; }
    public int? ModifiedBy { get; set; }
    public DateTime? ModifiedDate { get; set; }

    // A29-P5-01 §6.3 — support for a PO generated from a sale order line's deficit (§6.1). All
    // nullable: every PO up to this task is MANUAL and has none of these set. LinkedSoId/
    // LinkedSoLineId stay a plain scalar int rather than a real FK/relationship, matching
    // SaleOrderLine.LinkedPoId's own precedent for exactly this kind of soft cross-document link
    // within the same schema.
    public string   Source                    { get; set; } = "MANUAL"; // MANUAL | BACK_TO_BACK | DROP_SHIP | MIR
    public int?     LinkedSoLineId             { get; set; }
    public int?     LinkedSoId                 { get; set; }
    // logistics.Addresses.UUID — cross-module reference, no FK constraint, same convention as
    // SaleOrder.ShippingAddressId.
    public Guid?    CustomerShippingAddressId  { get; set; }
    public decimal? AutoGeneratedQty           { get; set; }
    public decimal? AutoGeneratedPrice         { get; set; }
    // suppliers.BusinessPartners.UUID — cross-module reference, no FK constraint.
    public Guid?    AutoSelectedSupplierId     { get; set; }

    public ICollection<PurchaseOrderLine> Lines { get; set; } = new List<PurchaseOrderLine>();
    public ICollection<PurchaseOrderPrLink> PrLinks { get; set; } = new List<PurchaseOrderPrLink>();
}

// A29-P5-03 §6.3 — values of PurchaseOrder.Source. A static class of constants rather than the
// [Code]-enum pattern SaleOrder uses, matching how this entity already handles Status (a plain
// string): nothing here needs parsing or validating an inbound code, only naming the values.
internal static class PurchaseOrderSources
{
    public const string Manual    = "MANUAL";
    public const string BackToBack = "BACK_TO_BACK";
    public const string DropShip  = "DROP_SHIP";
    public const string Mir       = "MIR";
}

internal class PurchaseOrderLine : ITenantScopedEntity
{
    public int Id { get; set; }
    public Guid UUID { get; set; }
    public Guid OrganizationId { get; set; }
    public int PurchaseOrderId { get; set; }
    public int LineNo { get; set; }
    public Guid? SourcePrLineUuid { get; set; } // UUID reference to pr_lines — no FK (cross-module safe)
    // PV-004 — references a ProductVariant, not a Product; every transactable line is priced
    // and received against a specific variant (SKU/barcode/price), even for single-variant products.
    public Guid? VariantUuid { get; set; }
    public string ItemDescription { get; set; } = string.Empty;
    public string? Specification { get; set; }
    public string? UnitOfMeasure { get; set; }
    public decimal Quantity { get; set; }
    public decimal UnitPrice { get; set; }
    public decimal LineTotal { get; set; }
    // RC-004 — set when a volume-discount suggestion (from the variant+supplier's rate card) is
    // accepted at PO creation. Stored for reference only — does not change LineTotal's calculation.
    public decimal? LineDiscountPct { get; set; }
    public decimal QtyReceived { get; set; }   // cumulative qty received across all GRNs
    public decimal QtyInvoiced { get; set; }   // cumulative qty invoiced across all approved invoices
    public DateTime? RequiredDate { get; set; }
    public string? LineNotes { get; set; }
    public string? BudgetCode { get; set; }
    public Guid? WarehouseId { get; set; }     // per-line override; null means use PO header DeliveryWarehouseId
    public string? WarehouseName { get; set; }
    // Decided at PO creation; inherited by the GRN line when goods are received — QC is
    // skipped entirely for lines where this is false.
    public bool RequiresInspection { get; set; } = true;
    public PurchaseOrder PurchaseOrder { get; set; } = null!;

    [System.ComponentModel.DataAnnotations.Schema.NotMapped]
    public Guid? EffectiveWarehouseId => WarehouseId ?? PurchaseOrder?.DeliveryWarehouseId;

    [System.ComponentModel.DataAnnotations.Schema.NotMapped]
    public string? EffectiveWarehouseName => WarehouseName ?? PurchaseOrder?.DeliveryWarehouseName;
}

internal class PurchaseOrderPrLink : ITenantScopedEntity
{
    public int Id { get; set; }
    public Guid OrganizationId { get; set; }
    public int PurchaseOrderId { get; set; }
    public Guid PrUuid { get; set; } // UUID reference to purchase_requisitions — no FK
    public PurchaseOrder PurchaseOrder { get; set; } = null!;
}
